/*
 * Silicon Laboratories Confidential
 * Copyright 2011 Silicon Laboratories, Inc.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!
 */

#include "bsp.h"


/*!
 * This function is used to handle the assertion of nIRQ of the si446x chip.
 *
 * @note This function can take up to 6 ms depending on the startup time of the
 * si446x chip.
 *
 */
void si446x_nirq_process(void)
{
	U8 si446x_ph_pend;
	U8 si446x_modem_pend;
	U8 si446x_chip_pend;
#ifdef SI446X_USER_CONFIG_USE_FRR_ABC_FOR_NIRQ
    //SEGMENT_VARIABLE(pendBits[3], U8, SEG_DATA);
	U8 pendBits[3];
    si446x_frr_a_read( );
#else
    si446x_get_int_status(0, 0, 0);
	si446x_ph_pend = Si446xCmd.GET_INT_STATUS.PH_PEND;
	si446x_modem_pend = Si446xCmd.GET_INT_STATUS.MODEM_PEND;
	si446x_chip_pend = Si446xCmd.GET_INT_STATUS.CHIP_PEND;
#endif
}
