@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


"F:\iar_710\common\bin\cspybat" "F:\iar_710\arm\bin\armproc.dll" "F:\iar_710\arm\bin\armsim2.dll"  %1 --plugin "F:\iar_710\arm\bin\armbat.dll" --device_macro "F:\iar_710\arm\config\debugger\ST\Trace_STM32F4xx.dmac" --backend -B "--endian=little" "--cpu=Cortex-M4F" "--fpu=VFPv4" "-p" "F:\iar_710\arm\CONFIG\debugger\ST\STM32F407VE.ddf" "--semihosting" "--device=STM32F407VE" "--multicore_nr_of_cores=1" 


